//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GvG_Core_Bot.Main.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GvG_Core_Bot.Main.Messages.CommandMessages", typeof(CommandMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels the current game. You cannot cancel the game though if it hasn&apos;t even started or has finished..
        /// </summary>
        internal static string CancelGameDesc {
            get {
                return ResourceManager.GetString("CancelGameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the server (and automatically cancels all games in the server.).
        /// </summary>
        internal static string DieDesc {
            get {
                return ResourceManager.GetString("DieDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a summary of the map, dependent on where you post this particular message. Civilians for example, only see public information (like reported poisoned tiles.) Gaia / Guardian / Occult Club recieves where each member would patrol, as well as information they know. (eg. where each member has supposedly patrolled, for OC, the location of Kagari in the map.) If you post it on PM to Kagari, you will see your Club info, as well as other personal info. (eg. for Lucia, you know where you poisoned your tiles [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisplayMapDesc {
            get {
                return ResourceManager.GetString("DisplayMapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If you indicate a specific tile, you will know more about that tile, including: status of that tile, and reported sightings..
        /// </summary>
        internal static string DisplayMapDesc_TileSummary {
            get {
                return ResourceManager.GetString("DisplayMapDesc_TileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a list with all the commands. (Prefix is %).
        /// </summary>
        internal static string HelpDesc {
            get {
                return ResourceManager.GetString("HelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Applies a search filter for either the content or the alias used. If you specify exactly a specific module, it will display all commands of that module..
        /// </summary>
        internal static string HelpDesc_SearchSummary {
            get {
                return ResourceManager.GetString("HelpDesc_SearchSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joins a faction (OC / Gaia / Guardian). You cannot join if you&apos;re on a faction..
        /// </summary>
        internal static string JoinDesc {
            get {
                return ResourceManager.GetString("JoinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module contains all generic movements..
        /// </summary>
        internal static string MovementDesc {
            get {
                return ResourceManager.GetString("MovementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the role that must be muted / unmuted..
        /// </summary>
        internal static string MuteAll_RoleSummary {
            get {
                return ResourceManager.GetString("MuteAll_RoleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes all users with a specified role..
        /// </summary>
        internal static string MuteAllDesc {
            get {
                return ResourceManager.GetString("MuteAllDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used during the Idle Phase. You will patrol a specified area, example 5x4 (starting from the top-left-most tile, five tiles right, then four tiles down.) You can change your patrol command until the end of the Idle Phase. Insert commas between the positions to perform a multi-patrol with relevant characters (like Chihaya &amp; Sakuya). Patrol prioritizes a PM to Kagari, and if you had PM&apos;d Kagari within the Phase, it will ignore all other patrol commands in the corresponding public channels. (Useful for bluffin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatrolDesc {
            get {
                return ResourceManager.GetString("PatrolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the patrol string. The format is XxY where X is from the left-most-tile going right, and Y is from the top-most tile going down. Add a comma for multiple patrol tiles. eg.: 1x1,2x2,3x3.
        /// </summary>
        internal static string PatrolDesc_RemainderSummary {
            get {
                return ResourceManager.GetString("PatrolDesc_RemainderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Only relevant if you are participating in multiple games (off the same bot). Indicates what server you&apos;re referring to. (eg. if you are playing a game in both the RIM server and a similar server, you have to indicate rewrite_ignis_memoria if you need to perform a patrol in that server..
        /// </summary>
        internal static string PatrolDesc_ServerSummary {
            get {
                return ResourceManager.GetString("PatrolDesc_ServerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you quit your current faction, if any..
        /// </summary>
        internal static string QuitDesc {
            get {
                return ResourceManager.GetString("QuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current status of the game; shows more if you&apos;re the Server Owner, or Bot Owner..
        /// </summary>
        internal static string StatusDesc {
            get {
                return ResourceManager.GetString("StatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmutes all users with a specified role..
        /// </summary>
        internal static string UnMuteAllDesc {
            get {
                return ResourceManager.GetString("UnMuteAllDesc", resourceCulture);
            }
        }
    }
}
