//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GvG_Core_Bot.Main.Messages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GvG_Core_Bot.Main.Messages.ResultMessages", typeof(ResultMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Crunchy Kagarin, signing off!&quot;.
        /// </summary>
        public static string BotIsOffline {
            get {
                return ResourceManager.GetString("BotIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Crunchy Kagarin, on the scene!&quot;.
        /// </summary>
        public static string BotIsOnline {
            get {
                return ResourceManager.GetString("BotIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Error.
        /// </summary>
        public static string ContError {
            get {
                return ResourceManager.GetString("ContError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t authorized to continue the game, paused or not..
        /// </summary>
        public static string ContError_NotAuthorized {
            get {
                return ResourceManager.GetString("ContError_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to continue an already continuing game..
        /// </summary>
        public static string ContError_NotPaused {
            get {
                return ResourceManager.GetString("ContError_NotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Continued].
        /// </summary>
        public static string ContSuccess {
            get {
                return ResourceManager.GetString("ContSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully continued the game..
        /// </summary>
        public static string ContSuccess_Desc {
            get {
                return ResourceManager.GetString("ContSuccess_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to create a game when there&apos;s already an ongoing game..
        /// </summary>
        public static string CreateGameException_OngoingGame {
            get {
                return ResourceManager.GetString("CreateGameException_OngoingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gaia VS Guardians Game!.
        /// </summary>
        public static string CreateGameSuccess {
            get {
                return ResourceManager.GetString("CreateGameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is starting a game of GvG! If anyone wants to join, type &quot;%join_game&quot; (without the quotes)..
        /// </summary>
        public static string CreateGameSuccess_Desc {
            get {
                return ResourceManager.GetString("CreateGameSuccess_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Error.
        /// </summary>
        public static string PatrolError {
            get {
                return ResourceManager.GetString("PatrolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t a GvG player at all..
        /// </summary>
        public static string PatrolError_NotInGame {
            get {
                return ResourceManager.GetString("PatrolError_NotInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tile code is invalid. Please use the proper code (number)x(number)..
        /// </summary>
        public static string PatrolError_ParseError {
            get {
                return ResourceManager.GetString("PatrolError_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Error.
        /// </summary>
        public static string PauseError {
            get {
                return ResourceManager.GetString("PauseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to pause an already paused game..
        /// </summary>
        public static string PauseError_AlreadyPaused {
            get {
                return ResourceManager.GetString("PauseError_AlreadyPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to pause a cancelled game..
        /// </summary>
        public static string PauseError_CancelledGame {
            get {
                return ResourceManager.GetString("PauseError_CancelledGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to pause this game. Refer to {0}..
        /// </summary>
        public static string PauseError_NotAuthorized {
            get {
                return ResourceManager.GetString("PauseError_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Paused].
        /// </summary>
        public static string PauseSuccess {
            get {
                return ResourceManager.GetString("PauseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully paused the game..
        /// </summary>
        public static string PauseSuccess_Desc {
            get {
                return ResourceManager.GetString("PauseSuccess_Desc", resourceCulture);
            }
        }
    }
}
