//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GvG_Core_Bot.Main.Database.Models {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoleDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GvG_Core_Bot.Main.Database.Models.RoleDescriptions", typeof(RoleDescriptions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are two &quot;familiars&quot; Kotarou found inside the maze of the school grounds. They&apos;re presumably from garbage, but they are surprisingly sentinent enough to be comedic relief. Nontheless, they&apos;re Kotarou&apos;s trusty side-kick... if you somewhat discount the anime timeline..
        /// </summary>
        public static string GilAndPanaDesc {
            get {
                return ResourceManager.GetString("GilAndPanaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the avatar of the Earth, the one single judge if humanity would live or you would have to re-initiate evolution. You are bound by your duty to examine the humans and observe their lives and emotions. However, you require fond memories so that you would not have to re-initiate Salvation..
        /// </summary>
        public static string KagariDesc {
            get {
                return ResourceManager.GetString("KagariDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the supposed leader of the Occult Club, a simple club formed by 5 simple awkward friends who were separated by the lifelong war of two idealogies. Kagari goes to you to help her find fond memories, but can you do it?.
        /// </summary>
        public static string KotarouDesc {
            get {
                return ResourceManager.GetString("KotarouDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the rather enigmatic Druid, who, as a child, lost her parents and &quot;revived&quot; them as familiars. You are tasked to protect the Key (Kagari). As you&apos;ve been preparing for so long, you&apos;ve erected Barriers around the Forest to protect the Key from anyone, until she supposedly executes Salvation, whatever that entails for humanity..
        /// </summary>
        public static string KotoriDesc {
            get {
                return ResourceManager.GetString("KotoriDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a normal civilian living in Kazamatsuri City. Living with a rather high wage, you occassionally tour around the luscious city filled, not only with science and environmental breakthroughs, but with a staggeringly large belief in the occult..
        /// </summary>
        public static string NormalCivilianDesc {
            get {
                return ResourceManager.GetString("NormalCivilianDesc", resourceCulture);
            }
        }
    }
}
